
import java.awt.BorderLayout; 
import java.awt.Dimension;
import java.util.Locale;
import javax.swing.JOptionPane;
import static javax.swing.SwingConstants.NORTH;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;        
        
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Juand
 */
public class Lab0501 extends javax.swing.JFrame {

    /**
     * Creates new form Lab0501
     */
    public Lab0501() {
        initComponents();
    }
    
    String item1="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Box1 = new javax.swing.JComboBox<>();
        acept_btn = new javax.swing.JButton();
        barras_bnt = new javax.swing.JButton();
        torta_btn = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Estadistica de medicamentos");

        Box1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "Medicamentos por concentración" }));
        Box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box1ActionPerformed(evt);
            }
        });

        acept_btn.setText("Aceptar");
        acept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acept_btnActionPerformed(evt);
            }
        });

        barras_bnt.setText("Grafica de barras");
        barras_bnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barras_bntActionPerformed(evt);
            }
        });

        torta_btn.setText("Grafica de torta");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(barras_bnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(torta_btn)
                .addGap(92, 92, 92))
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(acept_btn))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(Box1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Box1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acept_btn)
                .addGap(113, 113, 113)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barras_bnt)
                    .addComponent(torta_btn))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box1ActionPerformed

    private void acept_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acept_btnActionPerformed
        item1 = Box1.getSelectedItem().toString();
    }//GEN-LAST:event_acept_btnActionPerformed

    private void barras_bntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barras_bntActionPerformed
        if (item1.equalsIgnoreCase("Elige una opcion")|| item1.equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null, "OPCION INVALIDA");
        }
        if (item1.equalsIgnoreCase("Medicamentos por Concentración")){
            DefaultCategoryDataset dat = new DefaultCategoryDataset();
            
            dat.setValue(0.5, "Acetaminofen", "Tableta");
            dat.setValue(0.25, "Acetaminofen", "Supocitorio");
            dat.setValue(0.325, "Acetaminofen", "Tableta");
            dat.setValue(0.125, "Acetaminofen", "Granulado-Sachet");
            dat.setValue(0.005, "Acido Borico", "Polvo");
            dat.setValue(0.23, "ACEITE ESENCIAL DE EUCALIPTO + MENTOL  + ALCANFOR + SALICILATO DE METILO", "Ungüento");
            dat.setValue(0.188, "ACEITE ESENCIAL DE EUCALIPTO + MENTOL  + ALCANFOR + TRIMENTINA", "Ungüento");
            dat.setValue(0.47, "ACEITE DE HÍGADO DE PESCADO + OXIDO DE ZINC", "Crema Tópica");
            
            
             JFreeChart barras = ChartFactory.createBarChart(item1,"Formula Farmaceutica", "Concentración", dat , PlotOrientation.VERTICAL,true, true, false);
            ChartPanel panel1 = new ChartPanel(barras);
            panel1.setMouseWheelEnabled(true);
            panel2.setLayout(new BorderLayout());
            panel2.add(panel1, BorderLayout.NORTH);
            pack();
            repaint();
        }
        
       
    }//GEN-LAST:event_barras_bntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab0501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab0501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab0501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab0501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab0501().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box1;
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton acept_btn;
    private javax.swing.JButton barras_bnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JButton torta_btn;
    // End of variables declaration//GEN-END:variables
}
